theme: jekyll-theme-slate

title: "Bablu Kumar"
description: "I am a software developer, Python lover and data science enthusiast." 

```python
def foo():
    if not bar:
        return True
```      
